### ISSUE TITLE
what does this color mean?

### ISSUE THREAD

**Issue by liamxg** [imperialebola2018/exploratory-phylodynamics#1]
<img width="666" alt="image" src="https://github.com/imperialebola2018/exploratory-phylodynamics/assets/46078579/faca7bea-e2ba-4ee6-aa2c-667109ec1d82">

**Comment by emvolz** [comment]
This corresponds to the three "health zone" clusters indicated in the legend to the right. 
The code which produces this figure is here: https://github.com/imperialebola2018/exploratory-phylodynamics/blob/fbfdf2f9fcd17e2dd6601c7fe1f19b735000e852/README.Rmd#L188

**Comment by liamxg** [comment]
there are more than 3 colors, this is why I confused?
